### ISSUE TITLE
Docker image build caching

### ISSUE THREAD

**Issue by residentsummer** [practicalli/project-templates#26]
Hello. Thank you for creating Practicalli and for project templates in particular! IMO, these resources are very beneficial to new and returning clojure developers. Keep up the good work!

Now, to the issue. I was migrating an older project from boot-clj to your template and noticed, that many dependencies are being downloaded over and over during the `build uberjar` step. After some fiddling around I've figured out the following:

* `make deps` uses `:build` alias to preload deps
* `:build` alias replaces all project dependencies with just `clojure/tools.build`, which makes sense for `-T:build`
    ```
  :build
  {:replace-paths ["."]
   :replace-deps {io.github.clojure/tools.build
                  {:git/tag "v0.9.4" :git/sha "76b78fe"}}
   :ns-default build}
    ```

So, referring to the Dockerfile:

```Dockerfile
--- cut ---
# Cache and install Clojure dependencies
# Add before copying code to cache the layer even if code changes
COPY deps.edn Makefile /build/
RUN make deps                              <-- this step only downloads deps for :build alias

# Copy project to working directory
# .dockerignore file excludes all but essential files
COPY ./ /build


# ------------------------
# Test and Package application via Makefile
# `make all` calls `deps`, `test-ci`, `dist` and `clean` tasks
# using shared library cache mounted by pipeline process


# `dist` task packages Clojure service as an uberjar
# - creates: /build/practicalli-gameboard-api-service.jar
# - uses command `clojure -T:build uberjar`
RUN make dist                              <-- real project dependencies are downloaded here
--- cut ---
```

For my purposes, I've changed the Makefile `deps` target to the following to fetch all deps on `make deps` step:

```diff
  deps: deps.edn  ## Prepare dependencies for test and dist targets
  	$(info --------- Download test and service libraries ---------)
-  	clojure -P -X:build
+  	clojure -P -T:build
+  	clojure -P -M:run
```

Is it the intended behaviour to only fetch build tooling deps?

**Comment by practicalli-johnny** [comment]
The intent was to fetch all library dependencies in a single docker layer (project and build), so only fetching the build tooling deps is not a desired result. Thank you for reporting.

To get the main deps, test deps and build deps, then for the `:practicalli/service` template the `make deps` task could be

```Makefile
deps: deps.edn  ## Prepare dependencies for test and dist targets
	$(info --------- Download test and service libraries ---------)
	clojure -P -T:build && clojure -P -M:test/run
```

Or if running tests outside of docker, then drop the `:test/run` alias

```Makefile
deps: deps.edn  ## Prepare dependencies for test and dist targets
	$(info --------- Download test and service libraries ---------)
	clojure -P -T:build && clojure -P
```

I'll do some testing to confirm tomorrow and push changes in the next release

**Comment by practicalli-johnny** [comment]
The following release resolves this issue:

https://github.com/practicalli/project-templates/releases/tag/2024-04-20

Please report any further problems experienced, thank you.
