### ISSUE TITLE
Can't repro readme

### ISSUE THREAD

**Issue by vemv** [practicalli/project-templates#28]
Hi @practicalli-johnny ,

first time user here, not sure if I did something wrong.

```
~ $ clojure -Ttools install io.github.seancorfield/deps-new '{:git/tag "v0.5.2"}'  :as project-create
Cloning: https://github.com/seancorfield/deps-new.git
Checking out: https://github.com/seancorfield/deps-new.git at 253f32af67a87bc4f6d7f60e2a7353ca220a9d81
project-create: Installed io.github.seancorfield/deps-new v0.5.2
~ $ clojure -Tproject-create practicalli/service :name practicalli.gameboard/service
Cloning: https://github.com/clojure/tools.build.git
Checking out: https://github.com/clojure/tools.build.git at fe6b1405ba888720c813c7488c03880be73bbe20
Namespace could not be loaded: practicalli
```

Thanks  - V

**Comment by practicalli-johnny** [comment]
Ah, that is the part of the README that should have been deleted.  My apologies. 

I am not sure how to use Practicalli project-template when deps-new is used as a tool.  The previous examples in the README should be correct.

**Comment by vemv** [comment]
Thanks! 

So, this repo assumes [Practidalli Clojure CLI Config](https://practical.li/clojure/clojure-cli/practicalli-config/) is installed?

I do at times, but it also would be nice to have it in an isolated manner.

Perhaps an alias could be defined in https://github.com/practicalli/project-templates/blob/main/deps.edn so that one can clone this repo and use it to create new projects?

**Comment by practicalli-johnny** [comment]
Either include the Practicalli Clojure CLI config or add an alias to the `deps.edn` config for the project, as shown in the README.

I would need to investigate how to used a separate template with the deps-new as a tool (not sure if that is possible)

https://github.com/practicalli/project-templates?tab=readme-ov-file#alias-definition

**Comment by vemv** [comment]
Alright, thanks again!

**Comment by practicalli-johnny** [comment]
I'll update the README to make it clearer.  Thanks for highlighting that.

There are also some refinements I will be pushing around mulog and template generation later today.

**Comment by vemv** [comment]
Cheers. There's also a typo (`Practialli`, 2x)
